repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.7
    hooks:
      - id: cargo-sort
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [ file, rust ]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [ file, rust ]
        entry: cargo clippy --all-targets -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [ file, rust ]
        entry: cargo test
        pass_filenames: false

default_language_version:
  python: python3